name: Build Docker Image On Push (Both Tags and Branches)

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
      -
jobs:

  build_and_publish_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_type: [latest,alpine,postgres_12 ]
    steps:
      - uses: actions/checkout@v2

      - name: Clone  tools
        run: git clone --depth=1 --branch tools-transition-update-docker https://github.com/citusdata/tools.git tools

      - name: install dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev

      - name: install requirements
        run: python -m pip install -r tools/packaging_automation/requirements.txt

      - name: Build and Publish Docker Images
        run: python -m  tools.packaging_automation.publish_docker --github_ref "${GITHUB_REF}" --pipeline_trigger_type "${GITHUB_EVENT_NAME}" --exec_path "$(pwd)" --image_type ${{ matrix.image_type }}
