name: On Demand (Manual) Docker Image Build

on:
  workflow_dispatch:
    inputs:
      trigger_type:
        description: "Type of build which you want to trigger. Allowed values: main,tags,nightly"
      tag_name:
        description: "The tag name on the project repo to be released. It is mandatory if you select the trigger_type as 'tags' "
        default: ""

jobs:

  build_and_publish_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_type: [ latest,alpine,postgres_12,nightly ]
    steps:
      - uses: actions/checkout@v2

      - name: Clone  tools
        run: git clone https://github.com/citusdata/tools.git --branch tools-transition-update-docker --single-branch tools

      - name: install dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev

      - name: install requirements
        run: python -m pip install -r tools/packaging_automation/requirements.txt

      - name: Build and Publish Docker Images
        run: |
            python -m  tools.packaging_automation.publish_docker  --pipeline_trigger_type "${GITHUB_EVENT_NAME}" --exec_path "$(pwd)" --image_type ${{ matrix.image_type }} \
            --tag_name ${{ github.event.inputs.tag_name }} --manual_trigger_type ${{ github.event.inputs.tag_name }}
